### PR TITLE
Updated from network content collector

### PR DESCRIPTION
**Pull request by CaptTrews**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/322
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/323
Depends-On: https://github.com/ansible-network/ansible_collections.junipernetworks.junos/pull/2
Signed-off-by: CaptTrews <capttrews@gmail.com>

### CODE REVIEW

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 4ca0bee0f5191aa0679155779f4738abdc81ae80

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 4058678103898c936ecf4eb42fee9d1e195d1e4e

**Pull request merged**
